name: Deploy Voila App

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.15'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install voila

      - name: Set environment variable for GCP service account
        run: echo "GCP_SERVICE_ACCOUNT=${{ secrets.GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV

      - name: Run Voilà app
        run: |
          voila AguaTierra.ipynb --no-browser --port=8888


