name: Deploy Voilà app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.15

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Earth Engine
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}  # Secreto que configuraste en GitHub
      run: |
        python -m pip install earthengine-api
        python -m pip install jupyterlab

    - name: Run Voilà notebook
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        voila AguaTierra.ipynb --no-browser --port=8888

